# Custom Language File for Launcher Customizer

[ejs.app]
title = "Astra Land Launcher"

[ejs.landing]
mediaLinkURL = "#"
mediaGitHubURL = "https://github.com/SJSOFTS/AstraLandLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/DGf5T6eSwt"

[ejs.settings]
sourceGithubLink = "https://github.com/SJSOFTS/AstraLandLauncher"
supportLink = "https://github.com/SJSOFTS/AstraLandLauncher/issues"

[ejs.welcome]
welcomeHeader = "ASTRA LAND"
welcomeDescription = "한 마을에 떨어진 당신, 서버에서 용사, 농부, 낚시꾼등이 되어 서버에 일원이 되세요."
welcomeDescCTA = "항상 최고의 서비스를 제공하도록 노력하겠습니다."
